### ISSUE TITLE
Error with Preact-Router onRouteChange

### ISSUE THREAD

**Issue by oardi** [developit/preact-portal#6]
Components, that use Preact-Portal that are defined in Router cause the following error if "setState" is used in the Router´s "onChange".

error:
Uncaught (in promise) TypeError: Cannot read property 'parentNode' of null.

example that uses preact-router and preact-portal in a subcomponent:
http://jsfiddle.net/oardi/rorn3sph/

if "setState" is removed inside the function called by "onChange" in the example above, the error won´t show.

**Comment by timoxley** [comment]
@oardi workaround that seems to work fine is to override `Portal` `componentWillUnmount`: 

```js
Portal.prototype.componentWillUnmount = () => {} // noop
```

**Comment by javamonn** [comment]
I ran into this same error, though not due to a `setState` in `preact-router`'s `onChange`. I think this error occurs when the portal target is itself rendered by a Preact component and a re-render of that component causes the content that was "portaled" into the portal target to be removed.

My workaround was to move the portal target (in the jsfiddle, the `<div id=header-test />` element) into its own component, and implemented `shouldComponentUpdate` so as to always return `false` in order to prevent re-rendering. The portal content itself will still re-render in this case, we just want to prevent blowing away that content due to re-rendering the portal target.

**Comment by oardi** [comment]
I wanted to have the Portal target in the Parent (in the JsFiddle "App") because of one single header, that changes according to Router Components (i.e. other title, or inputs, searchbar and so on) and always stays at the top.
So moving it to its own component (in the JsFiddle "Home") wouldn´t make any benefit of the Portal use.

**Comment by javamonn** [comment]
Apologies, to be clear I meant to do something like this: http://jsfiddle.net/rorn3sph/5/

It's the same end structure as your example, we just wrap the bare element with it's own Preact component to prevent the re-render from blowing away the portaled content. What you render into the portal (in `Home`) will still be able to update in response to route changes fine, we just don't want to trigger a rerender of the portal container.

**Comment by oardi** [comment]
This is working fine. Thanks.
